### ISSUE TITLE
Formalize the way to generate bisulfite-seq methylation_profile 

### ISSUE THREAD

**Issue by dbujold** [IHEC/ihec-ecosystems#11]
From Sita:

> With regards to WGB-Seq standard tracks, we still need to define
> "methylation_profile." I believe "fractional_methylation_calls" on scale
> of 0 to 10 is supposed to be the standard. I am not sure if
> methylation_profile" is same as "fractional_methylation_calls." Either
> way the standard way of computing this needs to be documented.

**Comment by sitag** [comment]
Proposal posted at https://github.com/IHEC/ihec-ecosystems/blob/master/Fractional_Methylation_Proposal.md

**Comment by sitag** [comment]
Updated link to proposal: https://github.com/IHEC/ihec-ecosystems/blob/99f7af0878bd56b4aba4b1c5a9910b70cf403fc0/docs/Fractional_Methylation_Proposal.md

**Comment by sitag** [comment]
@dbujold Can you confirm that this is how IHEC datahubs are using?

**Comment by dbujold** [comment]
Hi Sita, it is not being used. To my knowledge, no group has changed their practices on the level of data they release, and WGB-Seq is the assay with the most divergence across groups. If we want to use this, it should be part of the epiMAP reanalysis.

**Comment by dzerbino** [comment]
So, is it fair to say that the ticket can be closed with respect to metadata spec update, and now needs to be enforced within EpiMap? Or do we need to extend the spec & validator in any way?

**Comment by sitag** [comment]
this doesn't have anything to do with metadata spec. this part of track hub spec - hence in ecosystem. i think we should adopt whatever simon is generating as part of gembs pipeline, since that's what integrative analysis will do. not sure what all epimap needs, and if those needs are separate.

**Comment by dzerbino** [comment]
Sounds like a plan

**Comment by dbujold** [comment]
EpiMAP will use the IHEC pipelines, so yes, including this in the GemBS pipeline will take care of EpiMAP as well.

**Comment by sitag** [comment]
closing.. will open when some progress is made.
