### ISSUE TITLE
MarkDown legibility

### ISSUE THREAD

**Issue by dzerbino** [IHEC/ihec-ecosystems#113]
We should simplify the MarkDown spec and ideally create a Jekyll page in time for the integrative analysis publication.

**Comment by sitag** [comment]
we are pretty close to autogenerating markdown. i second setting up the github pages repo.

**Comment by dzerbino** [comment]
That's great! Thanks for the update.

**Comment by sitag** [comment]
@dzerbino unfortunately I haven't worked on this in a while. i will pick this up again.

**Comment by sitag** [comment]
some issues with spec 2.2 have come up, fixing.
