### ISSUE TITLE
NOMe-seq experiments

### ISSUE THREAD

**Issue by quirinmanz** [IHEC/ihec-ecosystems#119]
Hi, 

I am trying to run the validator on NOMe-Seq experiment metadata files from the DEEP project and it fails.
I saw some related posts (#25 #26) but unfortunately, they did not help.

A minimal example XML file `NOME_example.xml` could look like this:
`<EXPERIMENT_SET>
   <EXPERIMENT accession="NOME_test" center_name="NOME_test">
        <TITLE />
        <STUDY_REF accession="NOME_test" refcenter="NOME_test" />
        <DESIGN>
            <DESIGN_DESCRIPTION />
            <SAMPLE_DESCRIPTOR accession="NOME_test" refcenter="NOME_test" refname="liver male adult (78 years)" />
            <LIBRARY_DESCRIPTOR>
            <LIBRARY_NAME>unspecified</LIBRARY_NAME>
            <LIBRARY_STRATEGY>NOME-seq</LIBRARY_STRATEGY>
            <LIBRARY_SOURCE>GENOMIC</LIBRARY_SOURCE>
            <LIBRARY_SELECTION>unspecified</LIBRARY_SELECTION>
            <LIBRARY_LAYOUT>
               <PAIRED NOMINAL_LENGTH="200"/>
            </LIBRARY_LAYOUT>
            <LIBRARY_CONSTRUCTION_PROTOCOL>NOME-Seq</LIBRARY_CONSTRUCTION_PROTOCOL>
         </LIBRARY_DESCRIPTOR>
      </DESIGN>
      <PLATFORM>
         <ILLUMINA>
            <INSTRUMENT_MODEL>Illumina HiSeq 2500</INSTRUMENT_MODEL>
         </ILLUMINA>
      </PLATFORM>
   </EXPERIMENT>
</EXPERIMENT_SET>`

This obviously fails with the following message:
`__invalid_xml:../NOME_example.xml
[{'-jsonlog': '../log.json', '-out': '../NOME_example.versioned.xml', '-config': 'path/to/ihec-ecosystems/version_metadata/config.json'}, ['../NOME_example.xml']]
xml validates [against:schemas/xml/SRA.experiment.xsd]... False [../experiments/reprocessed/NOME_example.xml]`

I have tried to use the library_strategy "OTHER", but this fails with the error:
`"invalid experiment_type : prevalidation"`
This is probably because "OTHER" gets returned in all caps from this [line](https://github.com/IHEC/ihec-ecosystems/blob/5f0359e53aaa0b0de8c56bab8dbc7e07cd103d99/version_metadata/egautils.py#L33).
But from this [line](https://github.com/IHEC/ihec-ecosystems/blob/5f0359e53aaa0b0de8c56bab8dbc7e07cd103d99/version_metadata/egautils.py#L25), I conclude that there are/were efforts to include NOMe-seq.

This pull request (#117) includes NOMe-Seq in the SRA.experiment.xsd file, but I think additional modifications to the experiment.json would be necessary.
Are you planning to include NOMe-seq or is there a workaround using OTHER?

Thanks in advance and for the great documentation!

Best,
Quirin

**Comment by sitag** [comment]
@quirinmanz updated https://github.com/IHEC/ihec-ecosystems/blob/master/version_metadata/egautils.py#L33 to return lowercase. It should find other in the schema now: https://github.com/IHEC/ihec-ecosystems/blob/master/schemas/json/2.0/experiment.json#L206

once we have attributes that we require for nome-seq, we can give nome-seq it's own branch in the schema; right now there isn't anything to check. 

i have also merged in https://github.com/IHEC/ihec-ecosystems/pull/117 

you can pass `-skip-updated-xml-validation` to skip xml validation: https://github.com/IHEC/ihec-ecosystems/blob/master/version_metadata/validate_main.py#L25 and change what xml you use for validation in https://github.com/IHEC/ihec-ecosystems/blob/master/version_metadata/config.json#L33 (you could also change what `config.json` is passed)

let me know if this works, if not then i will look into this more

**Comment by quirinmanz** [comment]
Thank you very much!

I can now successfully validate a NOMe-Seq experiment using `<LIBRARY_STRATEGY>NOMe-Seq</LIBRARY_STRATEGY>` and `<TAG>EXPERIMENT_TYPE</TAG><VALUE>Other</VALUE>`.

Still, I am not sure what EXPERIMENT_ONTOLOGY_CURIE to use since NOMe-seq does not seem to be included in the Ontology for Biomedical Investigations but only in [Experimental Factor Ontology](https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_0008830).
Can you help me with this or is it one of the reasons why it has not been included yet?

Best,
Quirin

**Comment by sitag** [comment]
@quirinmanz  Since there's no spec for NOMe-Seq yet, no matter what you submit, it will not validate against the latest spec (when the NOMEe-seq spec lands it will be 3.0 likely, so your current metadata won't validate against 3.0, but you will still get 2.0 validated as you have now). In the interest of being precise, I recommend that you use the EFO ontology for now. We will need to figure out how to deal with missing term in OBI ontology.
