### ISSUE TITLE
Consider adding minimum lengths to required fields

### ISSUE THREAD

**Issue by romgrk** [IHEC/ihec-ecosystems#16]
Currently, various fields are `required`. It is however possible to pass an empty string into a schema validator and the check is satisfied.

E.g.
https://github.com/IHEC/ihec-ecosystems/blob/94aa560ed5ad60396b380546fa6f381ad11fddd0/JSON_Data_Hub_Validator/schema/hub.json#L21

**Comment by dbujold** [comment]
Closing following outside discussion.
