### ISSUE TITLE
RNA-Seq required track spec

### ISSUE THREAD

**Issue by sitag** [IHEC/ihec-ecosystems#2]
The whole mRNA total RNA thing is still not settled with the metadata working group. So the example json hub is completely up in the air. Also, right now the required tracks for RNA are set to coverage, which from visual exploration is not really useful, and we don't generate that track, so I have used the rpkm tracks that we do have. The only thing that will change if we go ahead with coverage tracks is type and tag attribute.

**Comment by dbujold** [comment]
Indeed we first need to come to a decision for this before finalizing the spec. Same for the WGB-seq coverage vs signal vs etc.

**Comment by sitag** [comment]
This https://github.com/IHEC/ihec-assay-standards/issues/1 addresses at least the RNA-Seq issue.

**Comment by sitag** [comment]
I think this is now addressed by https://github.com/IHEC/ihec-ecosystems/blob/master/minimum_required_track_types.md , so we should close this.
