### ISSUE TITLE
validating without experiment_ontology_uri and experiment_type

### ISSUE THREAD

**Issue by sitag** [IHEC/ihec-ecosystems#21]
As discussed over email, with https://github.com/IHEC/ihec-ecosystems/blob/master/IHEC_Data_Hub/schema/experiment.json the first in https://github.com/IHEC/ihec-ecosystems/blob/version_metadata/version_metadata/examples/experiment.some_invalid.xml is validating but it shouldn't as it's missing both experiment_ontology_uri and experiment_type.

**Comment by dbujold** [comment]
Fixed and committed to master.
