### ISSUE TITLE
Add Transcription Factor ChIP-seq options

### ISSUE THREAD

**Issue by jahilton** [IHEC/ihec-ecosystems#27]
ChIP-seq experiments are currently restricted to 'ChIP Input' or 'ChIP Histone <target>'.
Here are suggested TF experiments to add to the list of options...
Transcription Factor CTCF
Transcription Factor POLR2A
Transcription Factor POLR2AphosphoS5
Transcription Factor EP300
Those are currently the only TF targets that ENCODE includes in Reference Epigenomes.

**Comment by martinhirst** [comment]
For consistency it might make sense to define as “ChIP Transcription Factor”

For all and then specify “CTCF” in a separate field as is done for specific histone mods?



On Feb 25, 2019, at 11:34 AM, jahilton <notifications@github.com<mailto:notifications@github.com>> wrote:


ChIP-seq experiments are currently restricted to 'ChIP Input' or 'ChIP Histone '.
Here are suggested TF experiments to add to the list of options...
Transcription Factor CTCF
Transcription Factor POLR2A
Transcription Factor POLR2AphosphoS5
Transcription Factor EP300
Those are currently the only TF targets that ENCODE includes in Reference Epigenomes.

**Comment by jahilton** [comment]
My interpretation was that currently, all ChIP experiments were LIBRARY_STRATEGY:'ChIP-Seq', but the EXPERIMENT_TYPE distinguished Input or Histone AND the specific histone mod
https://github.com/IHEC/ihec-metadata/blob/master/specs/Ihec_metadata_specification.md#chip-seq

**Comment by martinhirst** [comment]
ahh - sorry Jason.  Yes this would make sense then.

LIBRARY_STRATEGY:'ChIP-Seq’
EXPERIMENT_TYPE: ‘TF_target'



On Feb 26, 2019, at 9:35 AM, jahilton <notifications@github.com<mailto:notifications@github.com>> wrote:


My interpretation was that currently, all ChIP experiments were LIBRARY_STRATEGY:'ChIP-Seq', but the EXPERIMENT_TYPE distinguished Input or Histone AND the specific histone mod
https://github.com/IHEC/ihec-metadata/blob/master/specs/Ihec_metadata_specification.md#chip-seq

**Comment by sitag** [comment]
@dbujold will you be implementing this. The spec right now has pattern: https://github.com/IHEC/ihec-ecosystems/blob/master/version_metadata/json_schema/experiment.json#L123 
I am not sure how two patterns will be implemented (also that kind of defeats the purpose of controlled vocabulary, which we really should have here). Maybe you can provide a list of all histone mods you have seen and we can just add them all?

**Comment by jahilton** [comment]
For reference, here's the histone mods from Roadmap & ENCODE
`
H2AFZ
H2AK5ac
H2AK9ac
H2BK120ac
H2BK12ac
H2BK15ac
H2BK20ac
H2BK5ac
H3F3A
H3K14ac
H3K18ac
H3K23ac
H3K23me2
H3K27ac
H3K27me3
H3K36me3
H3K4ac
H3K4me1
H3K4me2
H3K4me3
H3K56ac
H3K79me1
H3K79me2
H3K9ac
H3K9me1
H3K9me2
H3K9me3
H3T11ph
H4K12ac
H4K20me1
H4K5ac
H4K8ac
H4K91ac
`

**Comment by makostadima** [comment]
No issue with the above suggestion from @jahilton from my side

> ChIP-seq experiments are currently restricted to 'ChIP Input' or 'ChIP Histone '.
> Here are suggested TF experiments to add to the list of options...
> Transcription Factor CTCF
> Transcription Factor POLR2A
> Transcription Factor POLR2AphosphoS5
> Transcription Factor EP300
> Those are currently the only TF targets that ENCODE includes in Reference Epigenomes.

Would you think that before we implement anything (either on the validator side or the metadata specs) should we bring it up on the next Ecosystems call?

**Comment by sitag** [comment]
@makostadima We need to send these out to the mailing list. We should only schedule them for the call if there's an issue raised. Otherwise it doesn't make sense to wait for the monthly call before implementing things.

**Comment by dbujold** [comment]
Hi all, I can make a pull request for this. But do we truly want to list all possibilities for both histones and TFBS? I mean, for instance, ENCODE focuses on a few TFBS as part of their reference epigenomes, but this list is very small compared to all possible experiments. Do we want to keep revisiting the spec every time we need to support a new TFBS?

**Comment by sitag** [comment]
I have no problem against add a larger list of TFs. It would all need to get documented. Not sure how large you would want to go. 

Also: I have noted on the metadata repo that it's frozen and new dev is at ecoystems.  I will copy the spec from metadata repo to ecosystems repo. Let include all this in candidate 1.1. spec under ecosystems repo.

**Comment by mlist** [comment]
I'm also a bit sceptical about listing all TFs in the controlled vocabulary since it's quite many. Might be more reasonable to document this in a free textfield. However, should we decide to go that way I would recommend using the target genes listed in the chip atlas for the controlled vocabulary: 

https://chip-atlas.org/target_genes 

At least this way we will likely have very few updates to this in the future.

**Comment by dbujold** [comment]
Maybe the right way could be to use existing ontologies to define TF and histone markers?

- SO seem to cover the histone marks that we have.
- ReTO (Regulation of Transcription Ontology) has a "gene" branch that might be usable? (although not sure how to express "POLR2AphosphoS5")...

**Comment by jahilton** [comment]
@dbujold & I discussed this briefly last month in Banff, specifically about the possibility of using the ENCODE list of TFs/histones are the 'approved' list. ENCODE does not have any list of possible targets in our codebase, but only in our metadata. 
https://www.encodeproject.org/search/?type=Target. For each target object, the label property would be the one to pull.

**Comment by dzerbino** [comment]
Decision of phone call 2/4/19: 
Short term decision: three fields with:
- Histones: empirical controlled vocab
- Gene name: HGNC symbol
- PTM: free text (for the moment)

I will start on a PR next week.

**Comment by dzerbino** [comment]
@sitag rightly pointed out that we need to provide a way to validate HGNC identifiers.

I will liaise with the HGNC developers for a programmatic solution.

**Comment by dzerbino** [comment]
HGNC offer APIs to determine whether a string is or was a valid HGNC symbol:
- Is it approved? http://rest.genenames.org/search/symbol/ELP1
- Was it approved? http://rest.genenames.org/search/prev_symbol/DYS

@sitag / @dbujold : would you be able to integrate this into the validator?

**Comment by dbujold** [comment]
I could have it added to the IHEC Data Hub validator, if we think it's worth it.

**Comment by dzerbino** [comment]
Could you please?

**Comment by sitag** [comment]
@dzerbino @dbujold  so the idea is that we want to see what's in experiment_target_tf key and validate it against HGNC via the API if EXPERIMENT_TYPE == '‘TF_target' . So PTM are still free text and not validated?

**Comment by dzerbino** [comment]
Correct, as agreed on the May 2nd call, PTM is free text for the moment.

**Comment by sitag** [comment]
@zxenia @dzerbino what is happening here? i would like to see this in master before i use the library functions exposed to add nicer error messages to metadata validator

**Comment by dzerbino** [comment]
If I am not mistaken, @zxenia has finished her PR and has requested review by @dbujold.

**Comment by zxenia** [comment]
Hi, this was implemented in PR #41. It checks, first, if the HGNC symbol is valid and in case it's not, checks if it was valid (approved) before.

**Comment by sitag** [comment]
@dzerbino @zxenia If there's nothing that further that needs to be discussed on this for next little bit, and wll the work has been subsumed in #41 , then can we log what we dd, what we are punting on and close this? We will reopen when needed.

**Comment by dzerbino** [comment]
I was thinking of closing the issues when #41 is pulled in, hopefully soon!

**Comment by sitag** [comment]
@dzerbino sounds good. before closing, can you summarise if what all remains unresolved as yet? or is it all addressed?

**Comment by dzerbino** [comment]
AFAIK:
- ChIP-Seq Targets are now correctly described in spec
- Spec will be correctly validated when #41 is pulled in
