### ISSUE TITLE
Replicates

### ISSUE THREAD

**Issue by dzerbino** [IHEC/ihec-ecosystems#29]
**Problem:** 
It is not always clear whether files can be merged.

**Consideration** 
In theory, things under the same EGAX can be merged but that is not guaranteed. Conversely, some files with different EGAX’s could be mergeable.

**Proposal** 
the centers need to indicate what merging strategies to use. 
E.g. : epirr_id : {  experiment type : {'merge' : [list of runs] }  }
This change would be optional for existing submissions
We will try to backfill/impute this information on a few key historical datasets
Required for future submissions

**Comment by dzerbino** [comment]
There are different types of files that can be merged in different ways:
- Read 1 vs 2 in read-pairs
- File broken up
- Technical replicates
- Biological replicates

How should we handle these? Do we allow technical/biological replicates within a single epigenome?

**Comment by sitag** [comment]
I don't follow 0 read 1 and read 2 from same run not being in the same RUN object should not be allowed. They always go in the same object. 

File broken up - not sure what you mean, This should also be flagged as invalid - the file is broken up, nothing we can do with that. Unless some other archive is allowing this.

We should only be addressing biological/technical replicates here.

**Comment by dzerbino** [comment]
Following our phone call, we will indeed limit ourselves to technical and biological replicates. 

I'll submit a PR shortly.

**Comment by dzerbino** [comment]
To be clear: 
- biological replicate -> different EpiRR ids
- technical replicates -> all under one EpiRR

Is that the consensus?

**Comment by dbujold** [comment]
That is how I see it as well.

Thank you,

David


On 2019-08-23 6:23 a.m., Daniel Zerbino wrote:

To be clear:

  *   biological replicate -> different EpiRR ids
  *   technical replicates -> all under one EpiRR

Is that the consensus?

**Comment by sitag** [comment]
sounds rights. we need a field to indicate what belongs to which technical replicate in the epirr.
the merging starting also becomes relevant here. so this ties into a few things.
do we still want a field where we can reference biological replicates?

**Comment by dzerbino** [comment]
@sitag : what you mean by 'what belongs to which technical replicate in the epirr'?

As I understand it, technical replicates are simply experiment objects of the same assay type linked to the sample sample. What subcomponents do we need to attach to them?

**Comment by sitag** [comment]
If a library is constructed twice, would that be a technical replicate? 
It may have two separate experiment objects both pointing to same sample. So which experiment object represent the same replicate needs to be tagged. Or am I missing something here?

**Comment by dzerbino** [comment]
(Apologies for the slow response)

Because library construction is part of the protocol, I believe that two libraries constructed from the same sample are technical replicates of each other. Experiments of the same assay run on these libraries would be technical replicates of each other.
