### ISSUE TITLE
'format' key not required under 'browser'

### ISSUE THREAD

**Issue by sitag** [IHEC/ihec-ecosystems#3]
With respect to https://github.com/IHEC/ihec-ecosystems/blob/master/JSON_Data_Hub_Validator/example1.json 

I believe we had this discussion before. The 'format' key is not required. Only a fixed format is supported for a track type, e.g. you cannot post bigwig data for 'peak_call' type. 

You can put it in there but it will not be used.

**Comment by dbujold** [comment]
Right. I'll fix this right away.

David

________________________________
