### ISSUE TITLE
User testing of submission process

### ISSUE THREAD

**Issue by dzerbino** [IHEC/ihec-ecosystems#35]
We observed discrepancies between the Markdown and JSON documents. 

To avoid having to manually check discrepancies between these to documents we propose to test software to automatically generate the Markdown from the JSON. 

The JSON would therefore become the master file. 

@sitag kindly offered to test this approach.

**Comment by sitag** [comment]
on it.

**Comment by sitag** [comment]
@dzerbino @dbujold Here is example of what we get out when we try to auto generate the documenattion: https://github.com/IHEC/ihec-ecosystems/blob/doc_from_json_schema/generated/doc/sample.schema.json.md ...not sure it's where we can simply replace the manual doc with auto generated one But then it's also using draft 04 schema that is in the master.

**Comment by dzerbino** [comment]
Hello @sitag ,

Thanks for looking into this! Evidently the parser is struggling with the parallel definitions.

Indeed, it would seem that we should be using `$id`, is there any reason we are using `id` instead?

Do you think this worth solution worth investigating further?

Cheers,

Daniel

**Comment by dzerbino** [comment]
As discussed in Banff, we need to seriously test everything about the submission process, and correct as we go along. Renaming issues.
