### ISSUE TITLE
json_hub_informal_description.md > track properties

### ISSUE THREAD

**Issue by dbujold** [IHEC/ihec-ecosystems#4]
Hi Sita, correct me if I'm mistaken, but I thought we said on the last call that "tag" wasn't necessary as it's only a shortened term for the track_type.

Also, I would suggest to leave the "strand" property always mandatory, and use "unstranded" when forward/reverse does not apply.

**Comment by dbujold** [comment]
Also, do we want "description_url" to be mandatory? I can add it to the mandatory fields list, just that it's optional in the UCSC track hubs. Either way is fine for me.

**Comment by sitag** [comment]
You are correct... we need to strip out tag from required fields and include that in the settings hash. 

I am not sure about 'description_url,' a fixed spec for analysis attributes that is detailed enough to reproduce the track will be very hard to define. Having a free form 'description_url' may be a nice escape hatch. Of course, we cannot enforce the level of detail on the description url, or if it's useful.

**Comment by dbujold** [comment]
Updated doc to remove "tag", and added description_url in the schema as an optional "uri" field.
