### ISSUE TITLE
Ontology choice for biomaterial_type = "Primary Cell Culture"

### ISSUE THREAD

**Issue by dbujold** [IHEC/ihec-ecosystems#47]
Right now, we define the ontology for SAMPLE_ONTOLOGY_URI based on the value of BIOMATERIAL_TYPE. It goes as follow:

    Cell Lines: Experimental Factor Ontology (EFO - https://www.ebi.ac.uk/efo/)
    Primary Cells: Cell Ontology (CL - http://cellontology.org)
    Primary Tissue: Uberon (UBERON - http://uberon.org)

This doesn't cover "Primary Cell Culture". We have a submitter who's preparing a metadata package for us, asking which ontology to use.

Looking at already submitted datasets in the portal, what was done so far:
DEEP: Use CL ontology
Blueprint: Use a semicolon-separated combination of CL and UBERON.

How should we address this case?

**Comment by dzerbino** [comment]
Looking at an example in BLUEPRINT: 
```http://purl.obolibrary.org/obo/CL_0001062;http://purl.obolibrary.org/obo/UBERON_0013756```
The CL URI points to `effector memory CD8-positive, alpha-beta T cell, terminally differentiated` while the UBERON URI points to `venous blood` (as opposed to cord blood). The second term thus enriches the first. 

This would suggest that when we allow for URI/CURIE we should in fact allow for concatenation of terms.

**Comment by dbujold** [comment]
I would rather support a list of terms, over concatenated terms... Otherwise we need to deal with separators.

**Comment by dzerbino** [comment]
Good point

**Comment by dbujold** [comment]
Is that supported by the EGA XMLs, though?

**Comment by dzerbino** [comment]
The attributes in question are not in the EGA spec, only the IHEC supplementary schema, so this should not create issues, no?

**Comment by sitag** [comment]
@dbujold  @dzerbino We can have repeated attributes in XML, these get parsed into lists in json.

**Comment by dbujold** [comment]
Would these repeated attributes be supported by the EGA?



On 2019-09-17 7:28 p.m., sitag wrote:

@dbujold<https://github.com/dbujold> @dzerbino<https://github.com/dzerbino> We can have repeated attributes in XML, these get parsed into lists in json.

**Comment by dbujold** [comment]
@dzerbino It's in the supplementary, yes, but these are stored in the attribute list in the XML document submitted to EGA.

**Comment by sitag** [comment]
@dbujold Pretty sure they are - recall that here gave been submissions with multiple sample ontologies attached in the past

**Comment by sitag** [comment]
> Looking at an example in BLUEPRINT:
> `http://purl.obolibrary.org/obo/CL_0001062;http://purl.obolibrary.org/obo/UBERON_0013756`
> The CL URI points to `effector memory CD8-positive, alpha-beta T cell, terminally differentiated` while the UBERON URI points to `venous blood` (as opposed to cord blood). The second term thus enriches the first.
> 
> This would suggest that when we allow for URI/CURIE we should in fact allow for concatenation of terms.

@dzerbino for exactly this reason we have reported things like:

...
<TAG>SAMPLEONTOLOGY_CURIE</TAG><VALUE>CL_0001062</VALUE>
<TAG>SAMPLEONTOLOGY_CURIE</TAG><VALUE>UBERON_0013756</VALUE>
...

@dbujold ...some care will be needed in handling this, depending on how xml is being parsed into json

**Comment by dzerbino** [comment]
To summarise: we are happy to replace simple CURIE strings with list of CURIEs, but we will have to keep an eye out during XML parsing.

Is this a fair summary?

**Comment by dzerbino** [comment]
Thinking more about @sitag 's last comment, if there is only one term provided, the XML parser would store it as a string, not as an array with only one element. Is anyone aware of a way to control this behaviour?

**Comment by sitag** [comment]
@dzerbino We wrote the parser, so we can handle that. As an aside, right now we parse everything into a list then only keep the first when validating. So it would be nice if we can make them all lists. This is why following lines in the code exists. 

https://github.com/IHEC/ihec-ecosystems/blob/7d23d314a12700e2ae981f4e28aa9a7ebe5c37ca/version_metadata/validate_sample.py#L11 
https://github.com/IHEC/ihec-ecosystems/blob/7d23d314a12700e2ae981f4e28aa9a7ebe5c37ca/version_metadata/utils.py#L71

We really should version the spec, and them move on to making these changes.

**Comment by dzerbino** [comment]
OK, making them lists.

**Comment by dzerbino** [comment]
PR #48 now pulled in.
