### ISSUE TITLE
ChIP-Input experiments not validating

### ISSUE THREAD

**Issue by sitag** [IHEC/ihec-ecosystems#49]
As per https://github.com/IHEC/ihec-ecosystems/blob/master/docs/metadata/1.0/Ihec_metadata_specification.md , things like

    <EXPERIMENT_ATTRIBUTE><TAG>CHIP_PROTOCOL</TAG><VALUE></VALUE></EXPERIMENT_ATTRIBUTE>

should validate. But when we parse this xml, the json gets None for "chip_protocol" and this fails against https://github.com/IHEC/ihec-ecosystems/blob/master/schemas/json/experiment.json#L135 as it is not a string.

**Comment by sitag** [comment]
@juettemann you might need to keep this in mind.

**Comment by dzerbino** [comment]
Hello  @sitag,

I'm not sure I agree with your reading of the spec. It says: `CHIP_PROTOCOL - The ChIP protocol used, or 'Input'.`. 

As I understand it, the XML example you provided should not validate. 

Cheers,

Daniel

**Comment by sitag** [comment]
@dzerbino Sorry, I meant nullable attributes like "CHIP_ANTIBODY"

**Comment by sitag** [comment]
@dzerbino There was some discussion (with @dbujold ) about supporting lists for attributes and not strings, in which case a NA value is an empty list (?) ..are we moving forward with lists or staying with strings?

**Comment by dzerbino** [comment]
Hello @sitag,

That's a good point: 
- My proposes solution is only a short term solution for EpiMap
- The lists (due V1.1) would be the long term one, assuming that NA is indeed an empty list

Cheers,

Daniel

**Comment by sitag** [comment]
submitted ["string", "null"] fix. 
https://github.com/IHEC/ihec-ecosystems/pull/60/commits/15bf5ec2e39d41423894ea19e913ae6c77afb44f

**Comment by dzerbino** [comment]
Can we close then?

**Comment by sitag** [comment]
sure ...assuming it looks good to you
