### ISSUE TITLE
Outreach plan

### ISSUE THREAD

**Issue by dzerbino** [IHEC/ihec-ecosystems#61]

**Comment by dzerbino** [comment]
As discussed at Banff, we need a larger outreach strategy, renaming issue.

**Comment by zxenia** [comment]
Hi all,
as a part of our outreach plan, I suggest adding the IHEC Data portal to [re3data.org](https://www.re3data.org/) - Registry of Research Data repositories. This will add to the portal discoverability.
It is a very straightforward procedure - we need to collect the metadata about the portal itself and submit it in the form on the registry website. Let me know what you think, I can prepare the metadata.

**Comment by dbujold** [comment]
Hi Ksenia, I think it's a good idea that looks quick to implement.

Thanks,

David



On 2020-03-03 10:15 a.m., Ksenia Zaytseva wrote:

Hi all,
as a part of our outreach plan, I suggest adding the IHEC Data portal to re3data.org<https://www.re3data.org/> - Registry of Research Data repositories. This will add to the portal discoverability.
It is a very straightforward procedure - we need to collect the metadata about the portal itself and submit it in the form on the registry website. Let me know what you think, I can prepare the metadata.
