### ISSUE TITLE
QC Flags 

### ISSUE THREAD

**Issue by dzerbino** [IHEC/ihec-ecosystems#65]
Background: 
One sample at CEMT had a QC flag (wrt mito content) but passed all other metrics. Because it is a rare sample, submitted to EGA. Many samples in IHEC do not pass QC but are not flagged (e.g. ChIP-Seq without Input)

Q: How do we submit sample with QC issues such that downstream users are aware of them? 

Suggestion: 

- Add QC free text flag.
- Add EpiRR flag
- EpiMap to review historical datasets 
- Store results in EpiRR/Portal

**Comment by sitag** [comment]
implemented here: https://github.com/IHEC/ihec-ecosystems/blob/jan2020/schemas/json/1.1/experiment.json#L10 

this will correspond to QC_FLAGS in xml. docs will need to be updated. please review as part of https://github.com/IHEC/ihec-ecosystems/pull/60
