### ISSUE TITLE
CURIE in V1.0?

### ISSUE THREAD

**Issue by dzerbino** [IHEC/ihec-ecosystems#71]
The transition from Ontology URI to CURIE was merged into both V1.0 and V1.1, is that intentional? This will demand some mokeying about from all submitters. Should we (can we?) only apply to V1.1?

**Comment by dbujold** [comment]
I believe the original intent was to keep it for v1.1 only.

**Comment by martinhirst** [comment]
Agreed CURIE is a v1.1 feature - we should not roll back to v1 with this.  For those that already have OK, but not required under v1.0

**Comment by dzerbino** [comment]
OK, this sounds like a clear decision. 

@zxenia can you confirm that your validator can handle both CURIES and URI, depending on the spec version?

**Comment by zxenia** [comment]
@dzerbino Now ontology validation (PR #48) only can handle CURIE. It doesn't handle URI.
But it can be adapted to handle both.

**Comment by sitag** [comment]
@dzerbino / @zxenia curie applies to 1.1 and 1.0. 
curie change was coming out at time when we had no concept of versioning, so whoever updated it, updated it in place. Then later 1.0 and 1.1 schemas were made.

**Comment by dzerbino** [comment]
Yes, probably my fault, see PR #74
