### ISSUE TITLE
Sample attributes required?

### ISSUE THREAD

**Issue by dzerbino** [IHEC/ihec-ecosystems#72]
[2 years ago](https://github.com/IHEC/ihec-metadata/commit/6c0dfb383256280c614bdabfcc356bec2352017a) we added this statement to the spec:

> In order to pass IHEC metadata validation, all datasets submitted prior to 2018 must include all sample properties defined within each specific BIOMATERIAL_TYPE below.

This seems dubious. Should it not apply to submissions post 2018? Note that this change was not enforced in the JSON spec so this will catch people by surprise

**Comment by sitag** [comment]
@dzerbino 

> This seems dubious. 

No. This is indeed true. If this is not being reflected in the json spec then that's up to @dbujold . I went back and filled everything for the March 2018 data freeze.

**Comment by dzerbino** [comment]
Hello @sitag ,

Thanks for all the background you sent me by email. To summarise: 

- In 2018, it was decided that all the sample fields at the time were required. 
- you backfilled all the metadata

In conclusion, if we don't want to trigger a massive resubmission of 2018 data we should remove this statement and mark as required each attribute which was present in the spec in 2018. This would be unambiguous and backwards compatible. 

Do you agree?

**Comment by dbujold** [comment]
Yes, it makes sense to me, thanks.

**Comment by martinhirst** [comment]
I agree with @dzerbino.   

I assume then the spec prior to 2018 is V1 and current is V1.1.  This would make the distinction clear and the validation clean.

**Comment by sitag** [comment]
@dzerbino in 2018, i updated all our metadata to be v1.0 compliant for samples and experiments. i believe myrto was following up on other centres updating to v1.0; you may need to review myrto's notes on that.

**Comment by dzerbino** [comment]
Hello @sitag , IIRC, the plan is that Myrto did follow up on the centres to update to v1.0, but because the validator reports were not entirely clear, this has not been completed, effectively, this is what we are doing now.

**Comment by sitag** [comment]
@dzerbino i am certain that Myrto reached out to centres, but it's entirely possible that it was not finished. i believe @zxenia updated to validator were made a while back, so error messages should have been cleaned up since.
