### ISSUE TITLE
Molecule type

### ISSUE THREAD

**Issue by dzerbino** [IHEC/ihec-ecosystems#73]
[2 years ago](https://github.com/IHEC/ihec-metadata/commit/0beb7e648edfd06afc10fec96f3d5064a5968852) we added the following statement to the experiment spec:

> In order to pass IHEC metadata validation, all datasets submitted prior to 2018 __must__ include the following properties:
> 
> * LIBRARY_STRATEGY
> * EXPERIMENT_TYPE or EXPERIMENT_ONTOLOGY_URI
> * MOLECULE or MOLECULE_ONTOLOGY_URI, either defined in the experiment or sample object.

Should this not apply to submissions post 2018?

**Comment by sitag** [comment]
@dzerbino  post 1.0 everything is required, so this is implicit.

**Comment by dzerbino** [comment]
OK, can this now be rephrased to:

> In order to pass IHEC metadata validation, all datasets submitted must include 
> the following properties:
> 
> LIBRARY_STRATEGY
> EXPERIMENT_TYPE or EXPERIMENT_ONTOLOGY_URI
> MOLECULE or MOLECULE_ONTOLOGY_URI, in the experiment object (or the sample object for datasets prior to 2018).
