### ISSUE TITLE
UMI ChIP support

### ISSUE THREAD

**Issue by sitag** [IHEC/ihec-ecosystems#82]
We need experiment metadata attributes to track UMI ChIP; to start the discussion, from our side we would like to propose:

* `UMI_ENABLED`: True/False value indicating if UMI is used

* `UMI_READ_STRUCTURE`: String to describe how to demultiplex reads; we can standardize by using string used by Picard tools to demultiplex describe the read structure; e.g.`3M2S146T` : 3 molecular barcode, 2 skip, 146 template.

This is sort of tangential, but we are seeing 101 and 100 bp reads in fastqs; the last base likely being phasing base that is sometimes left on. We don't want to leave what we should do to guesswork w.r.t. whether the last base should be trimmed. To address this, we propose two additional attributes:

* `PHASING_BASE_TRIMMED`: We need metadata to clarify if the phasing base has been trimmed. 

* `READ_LENGTH`: Similarly, we need people to specify what the read length was/what is max that should be used for alignment (this definition can be explicit about phasing base being excluded, so disambiguate read length vs cycles). While we can look this up in the file, it's very helpful to have this reported, and this can be included in validation of `UMI_READ_STRUCTURE`

If we define things precisely, we likely need only one of these two attributes.

**Comment by sitag** [comment]
Note there's a xml blob in sra for describing read, I am not sure it's sufficiently flexible for what we need, and seems more complicated for simpler use cases, like just reporting read length, and people don't fill it,

**Comment by sitag** [comment]
@juettemann @dzerbino added here https://github.com/IHEC/ihec-ecosystems/blob/ec7f44958cc23b16227ef6ca4cb5b695a3c13083/version_metadata/exp_semantic_rules.py#L6-L35

**Comment by sitag** [comment]
We have gone forward with this spec: http://fulcrumgenomics.github.io/fgbio/tools/latest/ExtractUmisFromBam.html

**Comment by dzerbino** [comment]
PR pulled in
